CC      = gcc
PROF    = -O -g
NOCRYPT =
C_FLAGS =  -Wall $(PROF) $(NOCRYPT)
L_FLAGS =  $(PROF) -rdynamic
LIBS    = -lcrypt

O_FILES = act_comm.o act_hera.o act_info.o act_move.o act_obj.o act_wiz.o \
          ban.o comm.o const.o db.o db2.o effects.o fight.o flags.o handler.o \
          healer.o interp.o lookup.o magic.o magic2.o martial_art.o \
          mob_prog.o note.o obj_prog.o quest.o recycle.o save.o  skills.o \
          special.o tables.o update.o

# Vars for dependency files
DEP_FILES = $(O_FILES:.o=.d)

# Default target
evren: $(O_FILES)
	rm -f evren
	$(CC) $(L_FLAGS) -o evren $(O_FILES) $(LIBS)

# Pattern rule for compiling .c to .o with header dependency
%.o: %.c merc.h
	$(CC) -c $(C_FLAGS) $< -o $@
	$(CC) -M $(C_FLAGS) $< > $(<:.c=.d)

# Include dependency files, ignore errors if files don't exist yet
-include $(DEP_FILES)

clean: 
	rm -f $(O_FILES) $(DEP_FILES) evren
